// Instinct RPG Card Studio — secret config (committed once, NOT regenerated by build_app.py)
// This file holds the scoped Baserow site-token so the secret stays OUT of index.html.
// index.html reads window.IRPG_TOKEN from here.
//
// Annie: replace the placeholder below with your scoped Baserow token, then commit this file
// to the repo root alongside index.html. The token needs these scopes:
//   - Comments table: read + create + update + delete
//   - Versions table: read
//   (Cards are baked into index.html, so card read is NOT required.)
//
// Leaving it blank disables live comments/versions but the rest of the app still works.
window.IRPG_TOKEN = "PASTE_YOUR_SCOPED_BASEROW_TOKEN_HERE";
