#!/usr/bin/env python3
"""Build card-data.js from MCP list_table_rows JSON dumps."""
from __future__ import annotations

import json
import re
from datetime import date
from html import unescape
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "card-data.js"
TOOLS = Path.home() / ".cursor/projects/c-Users-Natha-Claude-Projects-Instinct-RPG-Design-Cowork-Project/agent-tools"

TYPE_ACCS = {"bond", "flaw", "ancestry", "background", "instinct", "connection", "any"}


def strip_html(html: str) -> str:
    t = re.sub(r"<[^>]+>", " ", html or "")
    return unescape(re.sub(r"\s+", " ", t)).strip()


def guess_class(html: str) -> str:
    m = re.search(r"\bacc-([a-z]+)\b", html or "")
    if m and m.group(1) not in TYPE_ACCS:
        return m.group(1)
    return "any"


def guess_type(html: str) -> str:
    caps = re.findall(r'class="cap cap-(?:accent|neutral)"[^>]*>([^<]+)<', html or "")
    for raw in caps:
        t = raw.strip()
        if t in {"Background", "Ancestry", "Bond", "Flaw", "Instinct", "Connection"}:
            return t
        if t in {"Act", "React", "Core"}:
            return t
        if t == "Ability":
            for raw2 in caps[caps.index(raw) + 1 :]:
                t2 = raw2.strip()
                if t2 in {"Act", "React"}:
                    return t2
    return ""


def flavor_plain(html: str) -> str:
    for pat in (
        r'<div class="instinct-preamble"[^>]*>(.*?)</div>',
        r'<div class="flv"[^>]*>(.*?)</div>',
        r'<div class="hdr-sub"[^>]*>(.*?)</div>',
    ):
        m = re.search(pat, html or "", re.S)
        if m:
            return strip_html(m.group(1))
    return ""


def effect_plain(html: str) -> str:
    m = re.search(r'<div class="cbody[^"]*"(.*)</div>\s*</div>\s*$', html or "", re.S)
    return strip_html(m.group(1)) if m else strip_html(html)


def row_to_card(r: dict) -> dict | None:
    status = (r.get("Status") or {}).get("value") if isinstance(r.get("Status"), dict) else r.get("Status")
    if (status or "").lower() == "legacy":
        return None
    html = r.get("HTML") or ""
    card_type = guess_type(html)
    ruleset = (r.get("Ruleset") or {}).get("value") if isinstance(r.get("Ruleset"), dict) else r.get("Ruleset")
    scope = "Core" if card_type == "Core" else (
        "boon" if card_type in {"Background", "Ancestry", "Bond", "Flaw", "Instinct", "Connection"} else "ability"
    )
    return {
        "id": r["id"],
        "Name": r.get("Name", ""),
        "Card_Key": r.get("Card_Key", ""),
        "Class": guess_class(html),
        "Card_Type": card_type,
        "Scope": scope,
        "Ruleset": ruleset or "base",
        "Status": status or "current",
        "Last_Rework_Date": r.get("Last_Rework_Date") or "",
        "HTML": html,
        "FlavorText_Plain": flavor_plain(html),
        "EffectText_Plain": effect_plain(html),
    }


def main() -> None:
    rows = []
    for p in sorted(TOOLS.glob("*.txt")):
        try:
            data = json.loads(p.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            continue
        if isinstance(data, dict) and "results" in data:
            rows.extend(data["results"])
    # dedupe by id
    by_id = {r["id"]: r for r in rows}
    cards = [c for r in by_id.values() if (c := row_to_card(r))]
    cards.sort(key=lambda c: c["id"])
    today = date.today().isoformat()
    header = (
        f"// Generated by scripts/build_card_data_from_dump.py — do not edit manually. Last updated: {today}\n"
        f"// Source: Baserow table 911939, Status=current ({len(cards)} cards)\n"
        f"// Regenerate: py -3 scripts/regenerate_card_data.py (with token) or MCP dump + this script\n"
    )
    OUT.write_text(header + "window.CARD_DATA = " + json.dumps(cards, separators=(",", ":")) + ";\n", encoding="utf-8")
    primal = next((c for c in cards if c["Card_Key"] == "primal-instinct"), None)
    print(f"Wrote {len(cards)} cards")
    if primal:
        print("primal fork-v1:", "fork-v1" in primal["HTML"])


if __name__ == "__main__":
    main()
