#!/usr/bin/env python3
"""Patch card-data.js with Paladin Oath cards (Vow layout, 5 oaths + templates)."""
from __future__ import annotations

import json
import re
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
OUT = ROOT / "card-data.js"

from scripts.build_oath_html import (  # noqa: E402
    OATHS,
    OATH_ROW_IDS,
    build,
    build_oath_template,
    build_patron_template,
)
from scripts.regenerate_card_data import flavor_plain, effect_plain, guess_class, guess_type  # noqa: E402

LEGACY_KEYS = {
    "oath-of-devotion-paladin-core",
    "oath-of-vengeance-paladin-core",
    "oath-of-the-crown-paladin-core",
    "conviction-defiance-paladin-core",
}

REWORK_DATE = "2026-06-29"  # v5: 6×6 pools + 3×2 grid


def card_obj(row_id: int, name: str, key: str, html: str) -> dict:
    card_type = guess_type(html)
    return {
        "id": row_id,
        "Name": name,
        "Card_Key": key,
        "Class": guess_class(html),
        "Card_Type": card_type,
        "Scope": "Core" if card_type == "Core" else "ability",
        "Ruleset": "base",
        "Status": "current",
        "Last_Rework_Date": REWORK_DATE,
        "HTML": html,
        "FlavorText_Plain": flavor_plain(html),
        "EffectText_Plain": effect_plain(html),
    }


def main() -> None:
    text = OUT.read_text(encoding="utf-8")
    m = re.search(r"window\.CARD_DATA\s*=\s*", text)
    if not m:
        raise SystemExit("CARD_DATA assignment not found")
    cards = json.loads(text[m.end() :].strip().rstrip(";"))

    cards = [c for c in cards if c.get("Card_Key") not in LEGACY_KEYS]
    by_id = {c["id"]: c for c in cards}

    all_oaths = list(OATHS)
    row_map = dict(OATH_ROW_IDS)

    for o in all_oaths:
        key = o["key"]
        row_id = row_map.get(key)
        if not row_id:
            continue
        by_id[row_id] = card_obj(row_id, o["name"], key, build(o))

    tpl_specs = [
        (row_map.get("oath-template-paladin-core"), "Oath Template", "oath-template-paladin-core", build_oath_template()),
        (row_map.get("patron-template-warlock-core"), "Patron Template", "patron-template-warlock-core", build_patron_template()),
    ]
    for row_id, name, key, html in tpl_specs:
        if row_id:
            by_id[row_id] = card_obj(row_id, name, key, html)

    cards = sorted(by_id.values(), key=lambda c: c["id"])
    today = date.today().isoformat()
    header = (
        f"// Generated by scripts/patch_card_data_oaths.py — do not edit manually. Last updated: {today}\n"
        f"// Source: Baserow table 911939 patch (Paladin Oath / Vow layout)\n"
        f"// Full regen: py -3 scripts/regenerate_card_data.py\n"
    )
    OUT.write_text(header + "window.CARD_DATA = " + json.dumps(cards, separators=(",", ":")) + ";\n", encoding="utf-8")
    print(f"Patched {OUT} — {len(cards)} cards")


if __name__ == "__main__":
    main()
