#!/usr/bin/env python3
"""Regenerate card-data.js from Baserow table 911939 (Status=current)."""
from __future__ import annotations

import json
import re
import urllib.request
from datetime import date
from html import unescape
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONFIG = ROOT / "config.js"
OUT = ROOT / "card-data.js"
API = "https://api.baserow.io/api/database/rows/table/911939/"
TYPE_ACCS = {"bond", "flaw", "ancestry", "background", "instinct", "connection", "any"}


def read_token() -> str:
    text = CONFIG.read_text(encoding="utf-8")
    m = re.search(r'IRPG_TOKEN\s*=\s*"([^"]*)"', text)
    return (m.group(1) if m else "").strip()


def strip_html(html: str) -> str:
    t = re.sub(r"<[^>]+>", " ", html or "")
    t = unescape(re.sub(r"\s+", " ", t)).strip()
    return t


def guess_class(html: str) -> str:
    m = re.search(r"\bacc-([a-z]+)\b", html or "")
    if m and m.group(1) not in TYPE_ACCS:
        return m.group(1)
    return "any"


def guess_type(html: str) -> str:
    caps = re.findall(r'class="cap cap-(?:accent|neutral)"[^>]*>([^<]+)<', html or "")
    for raw in caps:
        t = raw.strip()
        if t in {"Background", "Ancestry", "Bond", "Flaw", "Instinct", "Connection"}:
            return t
        if t in {"Act", "React", "Core", "Ability"}:
            if t == "Ability":
                continue
            return t
    if 'class="core-header"' in (html or ""):
        return "Core"
    return ""


def flavor_plain(html: str) -> str:
    for pat in (
        r'<div class="flv"[^>]*>(.*?)</div>',
        r'<div class="hdr-sub"[^>]*>(.*?)</div>',
        r'<div class="bf-flv"[^>]*>(.*?)</div>',
    ):
        m = re.search(pat, html or "", re.S)
        if m:
            return strip_html(m.group(1))
    return ""


def effect_plain(html: str) -> str:
    m = re.search(r'<div class="cbody[^"]*"(.*)</div>\s*</div>\s*$', html or "", re.S)
    if not m:
        m = re.search(r'<div class="card-body"(.*)</div>\s*<div class="idtag"', html or "", re.S)
    if not m:
        m = re.search(r'<div class="bf-body"(.*)</div>\s*</div>', html or "", re.S)
    return strip_html(m.group(1)) if m else strip_html(html)


def fetch_rows(token: str) -> list[dict]:
    rows: list[dict] = []
    url = API + "?user_field_names=true&size=200&filter__Status__single_select_equal=current"
    while url:
        req = urllib.request.Request(url, headers={"Authorization": f"Token {token}"})
        with urllib.request.urlopen(req) as resp:
            data = json.loads(resp.read().decode("utf-8"))
        rows.extend(data.get("results") or [])
        url = data.get("next")
        if url:
            url = url.replace("http://", "https://")
    return rows


def main() -> None:
    token = read_token()
    if not token or token == "PASTE_YOUR_SCOPED_BASEROW_TOKEN_HERE":
        raise SystemExit("Set window.IRPG_TOKEN in config.js before regenerating card-data.js")

    rows = fetch_rows(token)
    cards = []
    for r in rows:
        html = r.get("HTML") or ""
        status = (r.get("Status") or {}).get("value") if isinstance(r.get("Status"), dict) else r.get("Status")
        ruleset = (r.get("Ruleset") or {}).get("value") if isinstance(r.get("Ruleset"), dict) else r.get("Ruleset")
        card_type = guess_type(html)
        cards.append(
            {
                "id": r["id"],
                "Name": r.get("Name", ""),
                "Card_Key": r.get("Card_Key", ""),
                "Class": guess_class(html),
                "Card_Type": card_type,
                "Scope": "Core" if card_type == "Core" else ("boon" if card_type in {"Background", "Ancestry", "Bond", "Flaw", "Instinct", "Connection"} else "ability"),
                "Ruleset": ruleset or "base",
                "Status": status or "current",
                "Last_Rework_Date": r.get("Last_Rework_Date") or "",
                "HTML": html,
                "FlavorText_Plain": flavor_plain(html),
                "EffectText_Plain": effect_plain(html),
            }
        )

    today = date.today().isoformat()
    header = (
        f"// Generated by scripts/regenerate_card_data.py — do not edit manually. Last updated: {today}\n"
        f"// Source: Baserow table 911939, Status=current ({len(cards)} cards)\n"
        f'// Regenerate: py -3 scripts/regenerate_card_data.py\n'
    )
    OUT.write_text(header + "window.CARD_DATA = " + json.dumps(cards, separators=(",", ":")) + ";\n", encoding="utf-8")
    print(f"Wrote {len(cards)} cards to {OUT}")


if __name__ == "__main__":
    main()
